import { GuildMember, Role, User } from "discord.js";

export interface Traductions {
  ERROR_COMMAND_NOT_FOUND: string;
  ERROR_LINKED_TO_YOUR_DISCORD_ACCOUNT: string;
  ERROR_COMMAND_NOT_IN_GUILDCHANNEL: string;
  ABOUT_BOT: (botMember: User) => string;
  ERROR_SYNC_BOT: string;
  AUDIT_DONE: (dbRolesLength: number, botMember: GuildMember) => string;
  AUDIT_AUDITED_ROLES: (auditedDbRolesLength: number, botMember: GuildMember, roleList: string) => string;
  AUDIT_NON_MANAGEABLE_ROLES: (nonManageableManagedRolesSize: number, botMember: GuildMember, botRole: Role, roleList: string) => string;
  AUDIT_DANGEROUS_ROLES: (nonAuditedDbRolesLength: number, botMember: GuildMember, roleList: string) => string;
  AUDIT_EXTREME_DANGER: string;
  YOU_CAN_SEE_LOG: string;
  HELP_CHOOSE_CATEGORY: string;
  HELP_CHOOSE_CATEGORY_MESSAGE: string;
  HELP_COMMAND_NOT_FOUND: string;
  ERROR_MISSING_TAG_OR_QR: string;
  ERROR_INVALID_QR_CODE: string;
  ERROR_NO_TAG_PROVIDED: string;
  ERROR_PLAYER_NOT_FOUND: (tag: string) => string;
  LOG_TITLE: string;
  LOG_EMPTY: string;
  LOG_ADDED: string;
  LOG_REMOVED: string;
  UNLINK_ALREADY_UNLINKED: (username: string, guildName: string) => string;
  UNLINK_SUCCESS: (username: string, guildName: string) => string;
  ERROR_BOT_MISSING_PERMISSION: string;
  ERROR_BOT_ROLE_TOO_LOW: (targetName: string, targetRole: string) => string;
  ERROR_USER_ROLE_TOO_LOW: (targetName: string, targetRole: string, executorRole: string) => string;
  LINK_SUCCESS: (playerName: string, playerTag: string, username: string, guildName: string) => string;
  LINK_PENDING_MODERATOR: (playerName: string, playerTag: string) => string;
  LINK_TIMEOUT: string;
  LINK_APPROVED: (playerName: string, playerTag: string, username: string, guildName: string) => string;
  LINK_REJECTED: string;
  LINK_NO_VALIDATION: string
  NO_TROPHY_ROLE: string;
  TROPHY_ROLE_UPDATED: (removed: string, added: string) => string;
  NO_GRADE_ROLE: string;
  GRADE_ROLE_UPDATED: (removed: string, added: string) => string;
  NO_CLUB_ROLE: string;
  CLUB_ROLE_UPDATED: (removed: string, added: string) => string;
  NAME_UPDATED: (newName: string) => string;
  UPDATE_CLUB_NO_MATCH: (clubInput: string | null, guildName: string) => string;
  UPDATE_CLUB_START: string;
  UPDATE_CLUB_NOT_FOUND: (clubName: string, clubTag: string) => string;
  UPDATE_CLUB_MEMBERS_UPDATED: (emoji: string, countUpdated: number, clubName: string, countChecked: number, total: number) => string;
  UPDATE_CLUB_MEMBERS_ALREADY_UPDATED: (emoji: string, clubName: string, countChecked: number, total: number) => string;
  UPDATE_CLUB_ROLE_REMOVED: (count: number, roleName: string) => string;
  UPDATE_MEMBER_START: string;
  UPDATE_MEMBER_NO_PROFILE: (nickname: string) => string;
  UPDATE_MEMBER_NOT_FOUND: (tag: string) => string;
  UPDATE_MEMBER_ALL_UP_TO_DATE: (nickname: string) => string;
  UPDATE_MEMBER_NICKNAME_CHANGED: (oldName: string, newName: string) => string;
  ADD_CLUB_NOT_FOUND: (clubTag: string) => string;
  ADD_CLUB_SUCCESS: (clubName: string, clubTag: string, guildName: string) => string;
  AUTO_RENAME_ALREADY_ENABLED: string;
  AUTO_RENAME_ALREADY_DISABLED: string;
  AUTO_RENAME_ENABLED: string;
  AUTO_RENAME_DISABLED: string;
  SET_CLUB_ROLE_INVALID_ROLE: string;
  SET_CLUB_ROLE_MISSING_TAG: string;
  SET_CLUB_ROLE_NOT_FOUND: (clubTag: string) => string;
  SET_CLUB_ROLE_SUCCESS: (clubName: string, roleName: string) => string;
  SET_GRADE_ROLE_INVALID_ROLE: string;
  SET_GRADE_ROLE_INVALID_GRADE: string;
  SET_GRADE_ROLE_SUCCESS: (gradeLabel: string, roleName: string) => string;
  SET_TROPHY_ROLE_INVALID_ROLE: string;
  SET_TROPHY_ROLE_INVALID_TROPHIES: string;
  SET_TROPHY_ROLE_SUCCESS: (roleName: string, trophies: number) => string;
  VERIFY_ALREADY_ENABLED: string;
  VERIFY_ALREADY_DISABLED: string;
  VERIFY_ENABLED: string;
  VERIFY_DISABLE_WARNING: string;
  VERIFY_DISABLED: string;
  VERIFY_CANCELLED: string;
  VERIFY_TIMEOUT: string;
  REMOVE_CLUB_MISSING_TAG: string;
  REMOVE_CLUB_NOT_FOUND: (clubTag: string, guildName: string) => string;
  REMOVE_CLUB_SUCCESS: (clubName: string, clubTag: string, guildName: string) => string;
  REMOVE_GRADE_ROLE_INVALID_GRADE: string;
  REMOVE_GRADE_ROLE_ALREADY_REMOVED: (gradeLabel: string) => string;
  REMOVE_GRADE_ROLE_SUCCESS: (gradeLabel: string) => string;
  REMOVE_TROPHY_ROLE_NOT_FOUND: (roleId: string, guildName: string) => string;
  REMOVE_TROPHY_ROLE_SUCCESS: (trophies: number, roleId: string, guildName: string) => string;
  GET_AUTO_RENAME_ENABLED: string;
  GET_AUTO_RENAME_DISABLED: string;
  GET_CLUB_ROLE_EMPTY: (guildName: string) => string;
  GET_CLUB_ROLE_LIST: (guildName: string, count: number, list: string) => string;
  GET_CLUBS_EMPTY: (guildName: string) => string;
  GET_CLUBS_LIST: (guildName: string, count: number, list: string) => string;
  GET_GRADE_ROLE_EMPTY: (guildName: string) => string;
  GET_GRADE_ROLE_LIST: (
    guildName: string,
    president: string,
    vicePresident: string,
    senior: string,
    member: string
  ) => string;
  GET_TROPHY_ROLE_NOT_IN_GUILD: string;
  GET_TROPHY_ROLE_EMPTY: (guildName: string) => string;
  GET_TROPHY_ROLE_LIST: (guildName: string, list: string) => string;
  GET_VERIFY_ENABLED: string;
  GET_VERIFY_DISABLED: string;
  GET_PROFILE_MEMBER_NOT_FOUND: string;
  GET_PROFILE_NO_TAG: (nickname: string) => string;
  GET_PROFILE_NOT_FOUND: (tag: string) => string;
  GET_PROFILE_HEADER: (username: string, guildName: string, playerName: string, playerTag: string) => string;
  GET_PROFILE_TROPHIES_LINE: (trophies: number, status: string, role: Role | null | undefined, removed: string) => string;
  GET_PROFILE_CLUB_LINE: (clubName: string, clubTag: string, status: string, role: Role | null | undefined, removed: string) => string;
  GET_PROFILE_GRADE_LINE: (grade: string, status: string, role: Role | null | undefined, removed: string) => string;
  GET_PROFILE_REMINDER_UPDATE: string;
  GET_PROFILE_REMINDER_UP_TO_DATE: (nicknameStatus: boolean) => string;
  LABEL_NONE: string;
  LABEL_NO_ROLE: string;
  LABEL_PROFILE_OF: (playerName: string) => string;
  LABEL_TROPHIES: string;
  LABEL_CLUB: string;
  LABEL_GRADE: string;
  HELP_FIELD_COMMAND: string;
  HELP_FIELD_USAGE: string;
  HELP_CLUBS_DESCRIPTION: string;
  HELP_CLUBS_SET_CLUB: string;
  HELP_CLUBS_SET_CLUBROLE: string;
  HELP_CLUBS_GET_CLUBS: string;
  HELP_CLUBS_GET_CLUBROLES: string;
  HELP_CLUBS_REMOVE_CLUB: string;
  HELP_CLUBS_USAGE: string;
  HELP_AUDIT_DESCRIPTION: string;
  HELP_AUDIT_AUDIT: string;
  HELP_AUDIT_LOGS: string;
  HELP_CONFIG_DESCRIPTION: string;
  HELP_CONFIG_SET_VERIFY: string;
  HELP_CONFIG_GET_VERIFY: string;
  HELP_CONFIG_SET_AUTORENAME: string;
  HELP_CONFIG_GET_AUTORENAME: string;
  HELP_CATEGORY_CLUBS: string;
  HELP_CATEGORY_AUDIT: string;
  HELP_CATEGORY_CONFIG: string;
  HELP_CATEGORY_GRADES: string;
  HELP_CATEGORY_PROFILE: string;
  HELP_CATEGORY_TROPHIES: string;
  HELP_CATEGORY_UPDATE: string;
  HELP_GRADES_DESCRIPTION: string;
  HELP_GRADES_SET_GRADEROLE: string;
  HELP_GRADES_GET_GRADEROLES: string;
  HELP_GRADES_REMOVE_GRADEROLE: string;
  HELP_GRADES_USAGE: string;
  HELP_PROFILE_DESCRIPTION: string;
  HELP_PROFILE_LINK: string;
  HELP_PROFILE_UNLINK: string;
  HELP_PROFILE_GET_PROFILE: string;
  HELP_PROFILE_USAGE: string;
  HELP_TROPHIES_DESCRIPTION: string;
  HELP_TROPHIES_SET_TROPHYROLE: string;
  HELP_TROPHIES_GET_TROPHYROLES: string;
  HELP_TROPHIES_REMOVE_TROPHYROLE: string;
  HELP_TROPHIES_USAGE: string;
  HELP_UPDATE_DESCRIPTION: string;
  HELP_UPDATE_UPDATE: string;
  HELP_UPDATE_UPDATE_CLUB: string;
  LANG_ALREADY: string;
  LANG_CHANGED:(from: string) => string;
  LANG_NAME_WITH_EMOJI:(lang:string) => string;
  GET_LANG: string;
  HELP_COMMAND_DESCRIPTION: string;
  UNLINK_COMMAND_DESCRIPTION: string;
  UNLINK_OPTION_MEMBER_DESCRIPTION: string;
  LOG_COMMAND_DESCRIPTION: string;
  AUDIT_COMMAND_DESCRIPTION: string;
  ABOUT_COMMAND_DESCRIPTION: string;
  LINK_COMMAND_DESCRIPTION: string;
  LINK_OPTION_QRCODE_DESCRIPTION: string;
  LINK_OPTION_TAG_DESCRIPTION: string;
  LINK_OPTION_MEMBER_DESCRIPTION: string;
  SET_COMMAND_DESCRIPTION: string;
  SET_GRADEROLE_DESCRIPTION: string;
  SET_GRADEROLE_OPTION_GRADE_DESCRIPTION: string;
  SET_GRADEROLE_OPTION_ROLE_DESCRIPTION: string;
  SET_TROPHYROLE_DESCRIPTION: string;
  SET_TROPHYROLE_OPTION_TROPHIES_DESCRIPTION: string;
  SET_TROPHYROLE_OPTION_ROLE_DESCRIPTION: string;
  SET_CLUBROLE_DESCRIPTION: string;
  SET_CLUBROLE_OPTION_TAG_DESCRIPTION: string;
  SET_CLUBROLE_OPTION_ROLE_DESCRIPTION: string;
  SET_AUTORENAME_DESCRIPTION: string;
  SET_AUTORENAME_OPTION_RENAME_DESCRIPTION: string;
  SET_VERIFY_DESCRIPTION: string;
  SET_VERIFY_OPTION_VERIFY_DESCRIPTION: string;
  SET_CLUB_DESCRIPTION: string;
  SET_CLUB_OPTION_TAG_DESCRIPTION: string;
  SET_LANG_DESCRIPTION: string;
  SET_LANG_OPTION_LANG_DESCRIPTION: string;
  REMOVE_COMMAND_DESCRIPTION: string;
  REMOVE_CLUB_DESCRIPTION: string;
  REMOVE_CLUB_OPTION_CLUB_DESCRIPTION: string;
  REMOVE_TROPHYROLE_DESCRIPTION: string;
  REMOVE_TROPHYROLE_OPTION_PALIER_DESCRIPTION: string;
  REMOVE_GRADEROLE_DESCRIPTION: string;
  REMOVE_GRADEROLE_OPTION_GRADE_DESCRIPTION: string;
  GET_COMMAND_DESCRIPTION: string;
  GET_AUTORENAME_DESCRIPTION: string;
  GET_VERIFY_DESCRIPTION: string;
  GET_CLUBROLES_DESCRIPTION: string;
  GET_CLUBS_DESCRIPTION: string;
  GET_GRADEROLES_DESCRIPTION: string;
  GET_TROPHYROLES_DESCRIPTION: string;
  GET_PROFILE_DESCRIPTION: string;
  GET_PROFILE_OPTION_TAG_DESCRIPTION: string;
  GET_PROFILE_OPTION_MEMBER_DESCRIPTION: string;
  GET_LANG_DESCRIPTION: string;
  UPDATE_COMMAND_DESCRIPTION: string;
  UPDATE_PROFILE_DESCRIPTION: string;
  UPDATE_PROFILE_OPTION_MEMBER_DESCRIPTION: string;
  UPDATE_CLUB_DESCRIPTION: string;
  UPDATE_CLUB_OPTION_CLUB_DESCRIPTION: string;
  HELP_CONFIG_SET_LANG: string;
  HELP_CONFIG_GET_LANG: string;
  CONFIG_BOT: (botMember: User) => string;
  CONFIG_COMMAND_DESCRIPTION: string;
  HELP_CONFIG_CONFIG: string;
}